version: '2.2'
services:

  etcd:
    image: quay.io/coreos/etcd
    restart: always
    hostname: etcd
    container_name: etcd

    networks:
      - haproxy

    ports:
      - 23791:2379
      - 23801:2380

    volumes:
      - etcd:/etcd.etcd

    environment:
      ETCD_NAME: etcd
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: etcd=http://etcd:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379

  e3w:
    image: soyking/e3w
    hostname: e3w
    container_name: e3w

    networks:
      - haproxy

    volumes:
      - ./conf/config.default.ini:/app/conf/config.default.ini

    ports:
      - 8081:8080

    environment:
      GIN_MODE: release

    links:
      - etcd

  haproxy:
    image: haproxy-confd
    restart: always
    init: true
    hostname: haproxy
    container_name: haproxy

    networks:
      - haproxy

    ports:
      - 1000:1000
      - 8080:80
      - 8443:443

    environment:
      ETCD_NODE: http://etcd:2379
      KEY_PREFIX: /default

    links:
      - etcd

networks:
    haproxy:
      driver: bridge
      ipam:
        config:
          - subnet: 172.177.0.0/16

volumes:
  etcd:
